### ISSUE TITLE
GNormPlus <-> TagTog

### ISSUE THREAD

**Issue by ashishbaghudana** [ashishbaghudana/mthesis-ashish#27]
The purple highlighted ones are transcription factors.
The green highlighted ones general proteins/genes.

Does this seem okay?

![sample1](https://cloud.githubusercontent.com/assets/3714983/10390959/18cf1e32-6e7c-11e5-993c-9c3688842291.png)

![sample2](https://cloud.githubusercontent.com/assets/3714983/10391021/6aebe268-6e7c-11e5-90aa-7f57e4c1a2c4.png)

**Comment by juanmirocks** [comment]
Seems about right, but:

**Comment by juanmirocks** [comment]
But:
- AR abbreviation should be annotated
- PIAS should probably annotated + thing in parenthesis
- DJ1 binding protein should probably not be annotated
- ERalpha must be annotated separately. That is, all abbreviations

**Comment by ashishbaghudana** [comment]
https://github.com/ashishbaghudana/PubTator2Anndoc/

You can use this script to convert PubTator format to Anndoc. I've documented the module fairly well, so it should be easy to use.

**Comment by ashishbaghudana** [comment]
https://pypi.python.org/pypi/PubTator2Anndoc/0.1.0

Also updated on the PyPi repository.

**Comment by ashishbaghudana** [comment]
A small bug on TagTog, possibly because the text is HTML based. If any sentence contains double spaces, for instance, "ChIP analysis revealed that the CLOCK&nbsp;&nbsp;BMAL1&nbsp;&nbsp;CRY1 complex strongly occupies the promoter region of Gm129", HTML formatting automatically converts multiple spaces to a single space. I guess, the best way to overcome this would be to convert all spaces to &nbsp;

I didn't think of this when I wrote the conversion script, I hadn't expected cases where there would be double spacing, but this messes with the annotation in JSON.

**Comment by juanmirocks** [comment]
@ashishbaghudana awesome for the public python package! :) 

As for the possible bug. The current behavior was well thought of and is intentional. Certainly there may be a use case for preserving these spaces, but I cannot review this as of now in tagtog. I guess you could try to have the option in your own converter to either 1) preserve spaces (as of now, disregarding possible unalignments) or 2) delete extra spaces and work out the correct alignments. I think it should be doable.

Note that as of now any sequence of whitespace characters (including tabs) are substituted for 1 simple white space.
